apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: product-dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: product-dev project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: product-dev
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: apps/**/product-dev/config.yaml
        repoURL: https://github.com/rgarrigue/argocd-autopilot-test.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
    - git:
        files:
          - path: apps/**/product-dev/config_dir.yaml
        repoURL: https://github.com/rgarrigue/argocd-autopilot-test.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              directory:
                exclude: "{{ exclude }}"
                include: "{{ include }}"
                jsonnet: {}
                recurse: true
              repoURL: ""
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: "{{ path[1] }}"
      name: product-dev-{{ path[1] }}
      namespace: argocd
    spec:
      project: product-dev
      source:
        repoURL: https://github.com/rgarrigue/argocd-autopilot-test.git
        targetRevision: HEAD
        path: "{{ path }}/../../chart"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - ../../../common/values*.yaml
            - ../../common/values*.yaml
            - values*.yaml
      destination:
        namespace: "{{ destNamespace }}"
        server: "{{ destServer }}"
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
