apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product

helmCharts:
  - name: kutt
    repo: https://raw.githubusercontent.com/rgarrigue/helm-chart-kutt/main/docs
    includeCRDs: false
    valuesInline:
      replicatCount: 2
